[package]
name = "holium-runtime-cli"
version = "0.1.0"
authors = ["tchataigner <thomas@polyphene.io>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
clap = "3.0.0-beta.2"
holium-runtime-lib = { path = "../holium-runtime-lib" }
serde_json = "1.0.64"