[package]
name = "holium-runtime"
version = "0.1.0"
authors = ["tchataigner <thomas@polyphene.io>"]
edition = "2018"

[workspace]
members = [
    "holium-runtime-cli",
    "holium-runtime-lib",
    "holium-wasm",
    "tests/rust",
]

[dependencies]
