[package]
name = "holium-pipe"
version = "0.1.0"
authors = ["Polyphene <contact@polyphene.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getset = "0.1.1"
regex = "1.5.4"
thiserror = "1.0.25"