[package]
name = "holium-cli"
version = "1.0.0-alpha"
authors = ["Polyphene <contact@polyphene.io>"]
edition = "2018"

[dependencies]
holium = { path = "../api" }
clap = "^2.33"

[dev-dependencies]
assert_cmd = "^1.0.7"