[package]
name = "holium-wasm"
version = "0.1.0"
authors = ["tchataigner <thomas@polyphene.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
serde_json = { version = "1.0.64" }
thiserror = "1.0"