[package]
name = "holium"
version = "1.0.0-alpha"
authors = ["Polyphene <contact@polyphene.io>"]
edition = "2018"

[dependencies]
anyhow = "^1.0.42"
cid = "^0.7.0"
itertools = "^0.10.1"
serde_cbor = "^0.11.1"

[dev-dependencies]
hex = "^0.4.3"